name: inject test

on:
  workflow_dispatch:

jobs:
  build:
    name: attest with custom predicate type
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write

    steps:
      - uses: hmarr/debug-action@v2
      - name: snap
        run: |
          sudo snap search snappy
      - name: Build artifacts
        run: |
          mkdir -p subdir
          echo "single-subject" > subdir/artifact-1.bin
 
      - name: Attest artifact
        id: attest
        uses: actions/attest@main
        with:
          subject-path: 'subdir/artifact-1.bin'
          predicate-type: '";whoami;"test'
          predicate: '{}'
      - name: Check output
        run: |
          echo "${{ steps.attest.outputs.attestation-id }}"
          echo "${{ steps.attest.outputs.attestation-url }}"
